database-type: SQLITE
mysql:
  address: 'localhost:3306'
  username: 'mcitarewards'
  password: 'mcitarewards'
  database: 'mcitarewards'
  table_prefix: 'mir_'
server-name: slimecraft
ticks-announcer: 24000
ticks-checker: 12000
