main: me.fabrimat.minecraftitaliarewards.MinecraftItaliaRewards
name: MinecraftItaliaRewards
version: '${project.version}'
author: Fabrimat
softdepend: [PlaceholderAPI]
commands:
  premio:
    description: Comando per ricevere i premi
    permission: mcita.reward
    permission-message: You do not have permission!
    usage: /premio
  mcita:
    description: Comando per gestire il plugin
    permission: mcita.admin
    permission-message: You do not have permission!
    usage: /mcita
permissions:
  mcita.reward:
    description: Permette di ricevere il premio
    default: op